name: Cosmo Frontend CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Insert FDID in staticwebapp.config.json
        shell: pwsh
        env:
           FDID: ${{ secrets.FrontDoorId }}
        run: |
           $config = Get-Content cosmo-frontend/staticwebapp.config.json | ConvertFrom-Json
           $config.forwardingGateway.requiredHeaders['X-Azure-FDID'] = $Env:FDID
           $config | ConvertFrom-Json -Depth 4 | Out-File cosmo-frontend/staticwebapp.config.json
           
           Get-Content cosmo-frontend/staticwebapp.config.json
           
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_COSMO }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/cosmo-frontend"
          api_location: ""
          output_location: "dist"
