# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Cosmo Python CI/CD

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: 'ubuntu-latest'
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://istatcosmo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to registry
      env:
        BUILD_NUMBER: Build-${{ github.run_number }}
      uses: docker/build-push-action@v2
      with:
        BUILD_NUMBER: Build-${{ github.run_number }}
        push: true
        tags: istatcosmo.azurecr.io/cosmo-python-service:run-${{ github.run_number }},istatcosmo.azurecr.io/cosmo-python-service:latest
        context: ./cosmo-backend/python-server/
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
        BUILD_NUMBER: Build-${{ github.run_number }}
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'istat-cosmo-python'
        slot-name: 'production'
        env:
          aaa:""ll"
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_PYTHONSERVICE }}
        images: 'istatcosmo.azurecr.io/cosmo-python-service:run-${{ github.run_number }}'
